spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 940722
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
#      cluster-name: my-application  暂时先用自己本机的  如果不在本机上需要配置名字
mapper:
  not-empty: true
  identity: MYSQL
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: classpath:mapper/*Mapper.xml

#在控制台输出sql语句
logging:
  level:
    com.tzk.boot.blog.blogtzk.dao: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql